import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Haroon Rasheed': 'Haroon Rasheed',
          'View & Edit Profile': 'View & Edit Profile',
          'Favorites & Saved Searches': 'Favorites & Saved Searches',
          'Favorites & Saved Searches': 'Favorites & Saved Searches',
          'Orders': 'Orders',
          'Orders, Billing & invoices': 'Orders, Billing & invoices',
          'My Trash': 'My Trash',
          'Track your selling or buying \n delivery orders':
              'Track your selling or buying \n delivery orders',
          'Payments': 'Payments',
          'Manage your payments': 'Manage your payments',
          'Logout': 'Logout',
          'Logout Confirmation': 'Logout Confirmation',
          'Are you sure you want to logout?':
              'Are you sure you want to logout?',
          'Cancel': 'Cancel',
          'Yes': 'Yes',
          'Email': 'Email',
          'Please enter your email': 'Please enter your email',
          'Please enter a valid email address':
              'Please enter a valid email address',
          'Send OTP': 'Send OTP',
          'Email': 'Email',
          'Please enter your email': 'Please enter your email',
          'Please enter a valid email': 'Please enter a valid email',
          'Password': 'Password',
          'Login': 'Login',
          "Don't have an account?": "Don't have an account?",
          'Register': 'Register',
          'Forgot Password?': 'Forgot Password?',
          'Create New Password': 'Create New Password',
          'Enter New Password': 'Enter New Password',
          'Confirm Password': 'Confirm Password',
          'Change Password': 'Change Password',
          'Login': 'Login',
          'OTP Verification': 'OTP Verification',
          'Please enter the 4-digit OTP sent to your email.':
              'Please enter the 4-digit OTP sent to your email.',
          'OTP Verified': 'OTP Verified',
          'OTP Entered': 'OTP Entered',
          'Verify OTP': 'Verify OTP',
          'Create new password': 'Create new password',
          'Name is required': 'Name is required',
          'Email is required': 'Email is required',
          'Phone number is required': 'Phone number is required',
          'Password is required': 'Password is required',
          'SignUp': 'SignUp',
          'Please select a role': 'Please select a role',
          'Buyer': 'Buyer',
          'Seller': 'Seller',
          'You selected': 'You selected',
          'Buyer': 'Buyer',
          'Seller': 'Seller',
          'Please select a role': 'Please select a role',
          'You selected:': 'You selected:',
          'FAQ': 'FAQ',
          'Frequently Asked Questions': 'Frequently Asked Questions',
          'Do I need an account to buy or sell number plates?':
              'Do I need an account to buy or sell number plates?',
          'Yes, an account is required to buy or sell number plates.':
              'Yes, an account is required to buy or sell number plates.',
          'How can I list my number plate for sale?':
              'How can I list my number plate for sale?',
          'To list your number plate, log in to your account, click on "Post," provide the details, and your plate will be ready for sale.':
              'To list your number plate, log in to your account, click on "Post," provide the details, and your plate will be ready for sale.',
          'Will the app support multiple languages?':
              'Will the app support multiple languages?',
          'Yes, the app supports both English and Arabic.':
              'Yes, the app supports both English and Arabic.',
          'Is there a fee for listing my number plate?':
              'Is there a fee for listing my number plate?',
          'No, listing is free. However, transaction fees may apply on sales.':
              'No, listing is free. However, transaction fees may apply on sales.',
          'Can I edit my number plate listing after posting it?':
              'Can I edit my number plate listing after posting it?',
          'Yes, you can edit your listing details anytime from "My Listings."':
              'Yes, you can edit your listing details anytime from "My Listings."',
          'Is my personal information shared with other users?':
              'Is my personal information shared with other users?',
          'No, your personal information remains private. All communication is handled within the app.':
              'No, your personal information remains private. All communication is handled within the app.',
          'How do I delete my account if needed?':
              'How do I delete my account if needed?',
          'You can delete your account by going to "View Profile" > "Delete" and selecting the delete option.':
              'You can delete your account by going to "View Profile" > "Delete" and selecting the delete option.',
          'Car Number Plate': 'Car Number Plate',
          '50,000 Q.T': '50,000 Q.T',
          'Some Detail': 'Some Detail',
          'More Info': 'More Info',
          'Home': 'Home',
          'Chat': 'Chat',
          'My List': 'My List',
          'Account': 'Account',
          'Contact Seller': 'Contact Seller',
          'Book Now': 'Book Now',
          'Listed by Private User': 'Listed by Private User',
          'View Profile': 'View Profile',
          'Sell': 'Sell',
          'Details': 'Details',
          'Description': 'Description',
          'Some Detail': 'Some Detail',
          'More Info': 'More Info',
          'Confirm your password': 'Confirm your password',
          '"Complete your detail to access exclusive plate number in Qatar"':
              '"Complete your detail to access exclusive plate number in Qatar"',
          '"Enter your detail for seamless experience on Lusail Numbers"':
              '"Enter your detail for seamless experience on Lusail Numbers"',
          'Please select a role': 'Please select a role',
          'selectedRole': 'selectedRole',
          'Buyer': 'Buyer',
          'Seller': 'Seller',
          'Favorites & Saved \n Searches': 'Favorites & Saved \n Searches',
          'Orders, Billing, and invoices': 'Orders, Billing, and invoices',
          '"Welcome to Lusail Numbers - Your gateway to exclusive car plates in Qatar!"':
              '"Welcome to Lusail Numbers - Your gateway to exclusive car plates in Qatar!"',
          'Plate Number:': 'Plate Number:',
          'Owner Name:': 'Owner Name:',
          'Price:': 'Price:',
          "I am selling this my Qatar number plate because I don't need it anymore. Please help me and buy this number plate.":
              "I am selling this my Qatar number plate because I don't need it anymore. Please help me and buy this number plate.",
          'Listed by Private User:': 'Listed by Private User:',
          'Haroon Rasheed': 'Haroon Rasheed',
          'Joined in January 2023': 'Joined in January 2023',
          'View Profile   ': 'View Profile   ',
          'Gold Category': 'Gold Category',
          'Some Detail': 'Some Detail',
          'More Info': 'More Info',
          'Show Less': 'Show Less',
          'Load More': 'Load More',
          'Sell': 'Sell',
          'Product 1': 'Product 1',
          'Product 2': 'Product 2',
          'Product 3': 'Product 3',
          'Product 4': 'Product 4',
          'Product 5': 'Product 5',
          'Normal': 'Normal',
          'Vip': 'Vip',
          'Gold': 'Gold',
          'Silver': 'Silver',
          'Search': 'Search',
          'My List': 'My List',
          'dd': 'dd',
          'Account': 'Account',
          'All Products': 'All Products',
          'Browse Category': 'Browse Category',
          'Vip': 'Vip',
          'Car No Plate': 'Car No Plate',
          'SportCar': 'SportCar',
          'Sedan': 'Sedan',
          '   My Listing': '   My Listing',
          'All lists ': 'All lists ',
          'No Plate:': 'No Plate:',
          'Car Type:': 'Car Type:',
          '108 views': '108 views',
          '7 leads': '7 leads',
          'Pending': 'Pending',
          'Update': 'Update',
          'Delete': 'Delete',
          'Normal Category': 'Normal Category',
          'Vip Category': 'Vip Category',
          'Silver Category': 'Silver Category',
          'notifications_title': 'Notifications',
          'new_product': 'New product available in Normal category.',
          'silver_discount': 'Silver category items have a new discount.',
          'gold_sale': 'Gold category sale starting soon!',
          'vip_offers': 'VIP members get exclusive offers.',
          'just_now': 'Just now',
          'Chat Screen': 'Chat Screen',
          'User': 'User',
          'U': 'U',
          'This is a sample message for User ':
              'This is a sample message for User ',
          'This feature is available only for premium users. Upgrade to access.':
              'This feature is available only for premium users. Upgrade to access.',
          'Feature': 'Feature',
          'Upgrade': 'Upgrade',
          'Video Call': 'Video Call',
          'Audio Call': 'Audio Call',
          'Chat messages will appear here...':
              'Chat messages will appear here...',
          'Type your message...': 'Type your message...',
          'Send Message': 'Send Message',
          'Subscribe': 'Subscribe',
          'Subscription': 'Subscription',
          'subscription_title': 'Subscription',
          'subscription_message': 'You selected the @plan plan.',
          'ok': 'OK',
          'subscription_plans': 'Subscription Plans',
          'monthly_plan_title': 'Monthly Plan',
          'monthly_plan_price': '\$10/month',
          'six_months_plan_title': '6 Months Plan',
          'six_months_plan_price': '\$50/6 months',
          'yearly_plan_title': 'Yearly Plan',
          'yearly_plan_price': '\$90/year',
          'subscribe': 'Subscribe',
          'Pending....': 'Pending....',
          'This may take some time.Please be patient. Your request will be accepted within 24 hours.':
              'This may take some time.Please be patient. Your request will be accepted within 24 hours.',
          "Back": "Back",
          "Title": "Title",
          'Success': 'Success',
          "Plate_number": "Plate Number",
          "Issue_date": "Issue Date",
          "Location": "Location",
          "Price": "Price",
          "Description": "Description",
          "Post_now": "Post Now",
          "Choose_image": "Choose Image",
          "Please_enter_title": "Please enter a title",
          "Please_enter_plate_number": "Please enter a plate number",
          "Please_enter_date": "Please enter the date",
          "Please_enter_location": "Please enter a location",
          "Please_enter_price": "Please enter a price",
          "Please_enter_description": "Please enter a description",
          'Cars': 'Cars',
          'Number Plates': 'Number Plates',
          'Plate Number': 'Plate Number',
          'Please enter a title': 'Please enter a title',
          'Please enter a plate number': 'Please enter a plate number',
          'Issue Date': 'Issue Date',
          'MM': 'MM',
          'YYYY': 'YYYY',
          'Favorites & Saved': 'Favorites & Saved',
          'Please enter': 'Please enter',
          'Plate Number2': 'Plate Number2',
          'Please enter a second plate number':
              'Please enter a second plate number',
          'Please enter a location': 'Please enter a location',
          'Price': 'Price',
          'Please enter a price': 'Please enter a price',
          'Please enter a description': "Please enter a description",
          'Choose Image': 'Choose Image',
          'Order History': 'Order History',
          // 'order_history': 'Order History',
          'ID': 'ID',
          'Seller': 'Seller',
          'Enter Your Name': 'Enter Your Name',
          'Buyer': 'Buyer',
          'Date': 'Date',
          'Price': 'Price',
          'Status': 'Status',
          'Write something about yourself': 'Write something about yourself',
          'Something About You': 'Something About You',
          'Private plate 195700': 'Private plate 195700',
          'Select Status': 'Select Status',
          'New\nOrders': 'New\nOrders',
          'Inn\nProcess': 'Inn\nProcess',
          'Delivery': 'Delivery',
          'Gender': 'Gender',
          'Total\nDelivered': 'Total\nDelivered',
          'MeTrash': 'MeTrash',
          'Latest Orders': 'Latest Orders',
          'Monday, 11 November \n2024(GMT-5)':
              'Monday, 11 November \n2024(GMT-5)',
          'Sold': 'Sold',
          'Paid': 'Paid',
          'Unpaid': 'Unpaid',
          'Pending': 'Pending',
          'Revenue': 'Revenue',
          'Total Sales': 'Total Sales',
          'Listed Items': 'Listed Items',
          'Pending \nPayments': 'Pending \nPayments',
          'Payments': 'Payments',
          'Payment History': 'Payment History',
          'Basic Information': 'Basic Information',
          'Gallery': 'Gallery',
          'Camera': 'Camera',
          'Prefer Not to Say': 'Prefer Not to Say',
          'Male': 'Male',
          'Female': 'Female',
          'Date of Birth': 'Date of Birth',
          'DD/MM/YYYY': 'DD/MM/YYYY',
          'Phone Number': 'Phone Number',
          'Enter your phone number': 'Enter your phone number',
          'Email': 'Email',
          'Enter your email': 'Enter your email',
          'Bank Account': 'Bank Account',
          'Enter your bank account': 'Enter your bank account',
          'Save': 'Save',
          'Total Orders': 'Total Orders',
          'Total Sales': 'Total Sales',
          'Listed Items': 'Listed Items',
          'Pending \nPayments': 'Pending \nPayments',
          'Dashboard': 'Dashboard',
          'Menu': 'Menu',
          'Orders': 'Orders',
          'Product': 'Product',
          'Users': 'Users',
          'Payments': 'Payments',
          'Logout': 'Logout',
          'Search...': 'Search...',
          'New Orders': 'New Orders',
          'In Progress': 'In Progress',
          'Number Transferred': 'Number Transferred',
          'Total Transferred': 'Total Transferred',
          'Number Transfer': 'Number Transfer',
          'Accepted': 'Accepted',
          'Rejected': 'Rejected',
          'Orders': 'Orders',
          'UserId': 'UserId',
          'Picture': 'Picture',
          'Name': 'Name',
          '   Edit': '   Edit',
          '  Delete': '  Delete',
          'Send': 'Send',
          'Receive': 'Receive',
          'Remaining Balance': 'Remaining Balance',
          'Payments': 'Payments',
          'Product': 'Product',
          'Item Id': 'Item Id',
          'Owner Name': 'Owner Name',
          'Plate No': 'Plate No',
          'Learn more': 'Learn more',
          'Users': 'Users',
          'Search by Owner Name or ID': 'Search by Owner Name or ID',
          'You selected': 'You selected',
        },
        'ar_AE': {
          'You selected': 'لقد حددت:',
          'Search by Owner Name or ID': 'البحث حسب اسم المالك أو الهوية',
          'Users': 'المستخدمين',
          'Learn more': 'يتعلم أكثر',
          'Plate No': 'رقم اللوحة',
          'Owner Name': 'اسم المالك',
          'Item Id': 'معرف العنصر',
          'Product': 'منتج',
          'Payments': 'المدفوعات',
          'Remaining Balance': 'الرصيد المتبقي',
          'Receive': 'يستلم',
          'Send': 'يرسل',
          '  Delete': 'يمسح  ',
          '   Edit': 'يحرر   ',
          'Name': 'اسم',
          'Picture': 'صورة',
          'UserId': 'معرف المستخدم',
          'Orders': 'طلبات',
          'Rejected': 'مرفوض',
          'Accepted': 'مقبول',
          'Number Transfer': 'نقل الرقم',
          'Total Transferred': 'المجموع المنقول',
          'Number Transferred': 'تم نقل الرقم',
          'In Progress': 'في تَقَدم',
          'New Orders': 'الطلبات الجديدة',
          'Search...': 'يبحث...',
          'Logout': 'تسجيل الخروج',
          'Payments': 'المدفوعات',
          'Users': 'المستخدمين',
          'Product': 'منتج',
          'Orders': 'طلبات',
          'Menu': 'قائمة طعام',
          'Dashboard': 'لوحة القيادة',
          'Pending \nPayments': '\nالدفعات المعلقة',
          'Listed Items': 'العناصر المدرجة',
          'Total Sales': 'إجمالي المبيعات',
          'Total Orders': 'إجمالي الطلبات',
          'Save': 'يحفظ',
          'Enter your bank account': 'أدخل حسابك البنكي',
          'Bank Account': 'الحساب البنكي',
          'Enter your email': 'أدخل بريدك الإلكتروني',
          'Email': 'بريد إلكتروني',
          'Enter your phone number': 'أدخل رقم هاتفك',
          'Phone Number': 'رقم التليفون',
          'DD/MM/YYYY': 'يوم/شهر/سنة',
          'Date of Birth': 'تاريخ الميلاد',
          'Female': 'أنثى',
          'Haroon Rasheed': 'هارون الرشيد',
          'Male': 'ذكر',
          'Prefer Not to Say': 'تفضل عدم القول',
          'View & Edit Profile': 'عرض وتحرير الملف الشخصي',
          'Favorites & Saved Searches': 'المفضلة وعمليات البحث المحفوظة',
          'Orders': 'الطلبات',
          'Orders, Billing & invoices': 'الطلبات والفواتير والفواتير',
          'My Trash': 'سلة المهملات الخاصة بي',
          'Track your selling or buying \n delivery orders':
              'تتبع طلبات الشراء أو البيع الخاصة بك \n طلبات التوصيل',
          'Payments': 'المدفوعات',
          'Manage your payments': 'إدارة مدفوعاتك',
          'Logout': 'تسجيل الخروج',
          'Logout Confirmation': 'تأكيد تسجيل الخروج',
          'Are you sure you want to logout?':
              'هل أنت متأكد أنك تريد تسجيل الخروج؟',
          'Cancel': 'إلغاء',
          'Yes': 'نعم',
          'Gender': 'جنس',
          'Write something about yourself': 'أكتب شيئا عن نفسك',
          'Something About You': 'شيء عنك',
          'Email': 'البريد الإلكتروني',
          'Please enter your email': 'يرجى إدخال بريدك الإلكتروني',
          'Please enter a valid email address':
              'يرجى إدخال عنوان بريد إلكتروني صالح',
          'Send OTP': 'إرسال رمز التحقق',
          'Email': 'البريد الإلكتروني',
          'Please enter your email': 'يرجى إدخال بريدك الإلكتروني',
          'Please enter a valid email': 'يرجى إدخال بريد إلكتروني صالح',
          'Password': 'كلمة المرور',
          'Login': 'تسجيل الدخول',
          "Dont have an account?": 'ليس لديك حساب؟',
          'Register': 'تسجيل',
          'Forgot Password?': 'هل نسيت كلمة المرور؟',
          'Create New Password': 'إنشاء كلمة مرور جديدة',
          'Enter New Password': 'أدخل كلمة المرور الجديدة',
          'Confirm Password': 'تأكيد كلمة المرور',
          'Change Password': 'تغيير كلمة المرور',
          'Login': 'تسجيل الدخول',
          'OTP Verification': 'التحقق من OTP',
          'Please enter the 4-digit OTP sent to your email.':
              'يرجى إدخال رمز التحقق المكون من 4 أرقام المرسل إلى بريدك الإلكتروني.',
          'OTP Verified': 'تم التحقق من OTP',
          'OTP Entered': 'تم إدخال OTP',
          'Verify OTP': 'التحقق من OTP',
          'Create new password': 'إنشاء كلمة مرور جديدة',
          'Name': 'اسم',
          'Phone Number': 'رقم التليفون',
          'Select Your Role': 'حدد دورك',
          'SIGN IN': 'تسجيل الدخول',
          'Already have an account?': 'هل لديك حساب بالفعل؟',
          'Name is required': 'الاسم مطلوب',
          'Email is required': 'البريد الإلكتروني مطلوب',
          'Phone number is required': 'رقم الهاتف مطلوب',
          'Password is required': 'كلمة المرور مطلوبة',
          'SignUp': 'تسجيل',
          'Please select a role': 'يرجى اختيار دور',
          'Buyer': 'مشتري',
          'Seller': 'بائع',
          'You selected': 'لقد اخترت',
          'Buyer': 'مشتري',
          'Enter Your Name': 'أدخل اسمك',
          'Seller': 'بائع',
          'Please select a role': 'يرجى اختيار دور',
          'You selected:': 'لقد اخترت:',
          'Welcome': 'مرحباً',
          'FAQ': 'التعليمات',
          'Camera': 'آلة تصوير',
          'Frequently Asked Questions': 'الأسئلة المتكررة',
          'Do I need an account to buy or sell number plates?':
              'هل أحتاج إلى حساب لشراء أو بيع لوحات الأرقام؟',
          'Yes, an account is required to buy or sell number plates.':
              'نعم، الحساب مطلوب لشراء أو بيع لوحات الأرقام.',
          'How can I list my number plate for sale?':
              'كيف يمكنني إدراج لوحة الأرقام الخاصة بي للبيع؟',
          'To list your number plate, log in to your account, click on "Post," provide the details, and your plate will be ready for sale.':
              'لإدراج لوحة الأرقام الخاصة بك، قم بتسجيل الدخول إلى حسابك، انقر على "نشر"، قدم التفاصيل، وستكون لوحتك جاهزة للبيع.',
          'Will the app support multiple languages?':
              'هل يدعم التطبيق عدة لغات؟',
          'Yes, the app supports both English and Arabic.':
              'نعم، التطبيق يدعم كل من الإنجليزية والعربية.',
          'Is there a fee for listing my number plate?':
              'هل هناك رسوم لإدراج لوحة الأرقام الخاصة بي؟',
          'No, listing is free. However, transaction fees may apply on sales.':
              'لا، الإدراج مجاني. ومع ذلك، قد تنطبق رسوم المعاملات على المبيعات.',
          'Can I edit my number plate listing after posting it?':
              'هل يمكنني تعديل إدراج لوحة الأرقام الخاصة بي بعد نشرها؟',
          'Yes, you can edit your listing details anytime from "My Listings."':
              'نعم، يمكنك تعديل تفاصيل الإدراج في أي وقت من "إعلاناتي".',
          'Is my personal information shared with other users?':
              'هل تتم مشاركة معلوماتي الشخصية مع مستخدمين آخرين؟',
          'No, your personal information remains private. All communication is handled within the app.':
              'لا، تظل معلوماتك الشخصية خاصة. يتم التعامل مع جميع الاتصالات داخل التطبيق.',
          'How do I delete my account if needed?':
              'كيف يمكنني حذف حسابي إذا لزم الأمر؟',
          'You can delete your account by going to "View Profile" > "Delete" and selecting the delete option.':
              'يمكنك حذف حسابك عن طريق الذهاب إلى "عرض الملف الشخصي" > "حذف" واختيار خيار الحذف.',
          'Car Number Plate': 'لوحة رقم السيارة',
          '50,000 Q.T': '50,000 ريال قطري',
          'Some Detail': 'بعض التفاصيل',
          'More Info': 'مزيد من المعلومات',
          'Home': 'بيت',
          'Chat': 'الدردشة',
          'My List': 'قائمتي',
          'Account': 'الحساب',
          'Contact Seller': 'اتصل بالبائع',
          'Book Now': 'احجز الآن',
          'Listed by Private User': 'مدرج من قبل مستخدم خاص',
          'View Profile': 'عرض الملف الشخصي',
          'Sell': 'بيع',
          'Details': 'تفاصيل',
          'Description': 'وصف',
          'Some Detail': 'بعض التفاصيل',
          'More Info': 'مزيد من المعلومات',
          'Sports car': 'سيارة رياضية',
          'Number plate': 'لوحة أرقام',
          'Sports car | Number plate': 'سيارة رياضية | لوحة أرقام',
          'Bahawalpur, Punjab, Pakistan': 'باهاوالبور، البنجاب، باكستان',
          'Confirm your password': 'قم بتأكيد كلمة المرور الخاصة بك',
          '"Complete your detail to access exclusive plate number in Qatar"':
              '"أكمل التفاصيل الخاصة بك للوصول إلى رقم اللوحة الحصري في قطر"',
          '"Enter your detail for seamless experience on Lusail Numbers"':
              '"أدخل التفاصيل الخاصة بك لتجربة سلسة مع أرقام لوسيل"',
          'Please select a role': 'الرجاء تحديد دور',
          'selectedRole': 'الرجاء تحديد دور',
          'Buyer': 'المشتري',
          'Seller': 'بائع',
          'Favorites & Saved \n Searches': 'المفضلة وعمليات البحث المحفوظة \n',
          'Orders, Billing, and invoices': 'الطلبات والفواتير والفواتير',
          '"Welcome to Lusail Numbers - Your gateway to exclusive car plates in Qatar!"':
              '"مرحبًا بكم في أرقام لوسيل - بوابتك إلى لوحات السيارات الحصرية في قطر!"',
          'Plate Number:': 'رقم اللوحة:',
          'Owner Name:': 'اسم المالك:',
          'Price:': 'سعر:',
          "I am selling this my Qatar number plate because I don't need it anymore. Please help me and buy this number plate.":
              "أبيع هذه اللوحة الرقمية الخاصة بي في قطر لأنني لم أعد بحاجة إليها. الرجاء مساعدتي وشراء لوحة الرقم هذه.",
          'Listed by Private User:': 'مُدرج بواسطة مستخدم خاص:',
          'Haroon Rasheed': 'هارون الرشيد',
          'Joined in January 2023': 'تم الانضمام في يناير 2023',
          'View Profile   ': '   عرض الملف الشخصي',
          'Gold Category': 'الفئة الذهبية',
          'Some Detail': 'بعض التفاصيل',
          'More Info': 'مزيد من المعلومات',
          'Show Less': 'عرض أقل',
          'Load More': 'تحميل المزيد',
          'Sell': 'يبيع',
          'Product 1': 'المنتج 1',
          'Product 2': 'المنتج 2',
          'Product 3': 'المنتج 3',
          'Product 4': 'المنتج 4',
          'Product 5': 'المنتج 5',
          'Normal': 'طبيعي',
          'Vip': 'كبار الشخصيات',
          'Gold': 'ذهب',
          'Silver': 'فضي',
          'Search': 'يبحث',
          'My List': 'قائمتي',
          'Account': 'حساب',
          'Gallery': 'معرض',
          'All Products': 'جميع المنتجات',
          'Browse Category': 'تصفح الفئة',
          'Vip': 'كبار الشخصيات',
          'Car No Plate': 'سيارة لا لوحة',
          'SportCar': 'سيارة رياضية',
          'Sedan': 'سيدان',
          '   My Listing': 'قائمتي   ',
          'All lists ': ' جميع القوائم',
          'No Plate:': 'لا لوحة:',
          'Car Type:': 'نوع السيارة:',
          '108 views': '108 مشاهدات',
          '7 leads': '7 خيوط',
          'Pending': 'قيد الانتظار',
          'Update': 'تحديث',
          'Delete': 'يمسح',
          'Normal Category': 'الفئة العادية',
          'Vip Category': 'فئة كبار الشخصيات',
          'Silver Category': 'الفئة الفضية',
          'notifications_title': 'الإشعارات',
          'new_product': 'منتج جديد متوفر في فئة العادي.',
          'silver_discount': 'فئة الفضة تمتلك تخفيضات جديدة.',
          'gold_sale': 'عرض فئة الذهب يبدأ قريبًا!',
          'vip_offers': 'الأعضاء المميزون يحصلون على عروض حصرية.',
          'just_now': 'منذ لحظات',
          'Chat Screen': 'شاشة الدردشة',
          'User': 'مستخدم',
          'U': 'ش',
          'This is a sample message for User ': 'هذه رسالة نموذجية للمستخدم',
          'This feature is available only for premium users. Upgrade to access.':
              'هذه الميزة متاحة فقط للمستخدمين المميزين. الترقية للوصول.',
          'Feature': 'ميزة',
          'Upgrade': 'يرقي',
          'Video Call': 'مكالمة فيديو',
          'Audio Call': 'مكالمة صوتية',
          'Chat messages will appear here...': 'ستظهر هنا رسائل الدردشة...',
          'Type your message...': 'اكتب رسالتك...',
          'Send Message': 'أرسل رسالة',
          'Subscribe': 'يشترك',
          'Subscription': 'الاشتراك',
          'subscription_title': 'الاشتراك',
          'subscription_message': 'قمت باختيار خطة @plan.',
          'ok': 'حسناً',
          'subscription_plans': 'خطط الاشتراك',
          'monthly_plan_title': 'الخطة الشهرية',
          'monthly_plan_price': 'دولار 10/الشهر',
          'six_months_plan_title': 'خطة 6 أشهر',
          'six_months_plan_price': 'دولار 50/6 أشهر',
          'yearly_plan_title': 'الخطة السنوية',
          'yearly_plan_price': 'دولار 90/السنة',
          'subscribe': 'اشترك',
          'Pending....': 'قيد الانتظار....',
          'This may take some time.Please be patient. Your request will be accepted within 24 hours.':
              'قد يستغرق هذا بعض الوقت. يرجى التحلي بالصبر. سيتم قبول طلبك خلال 24 ساعة.',
          "Back": "رجوع",
          "Title": "عنوان",
          "Plate_number": "رقم اللوحة",
          "Issue_date": "تاريخ الإصدار",
          "Location": "الموقع",
          "Price": "السعر",
          "Description": "الوصف",
          "Post_now": "أنشر الآن",
          "Choose_image": "اختر صورة",
          'Cars': 'سيارات',
          'Number Plates': 'لوحات أرقام',
          'Plate Number': 'رقم اللوحة',
          'Please enter a title': 'الرجاء إدخال عنوان',
          'Please enter a plate number': 'الرجاء إدخال رقم اللوحة',
          'Issue Date': 'تاريخ الإصدار',
          'dd': 'د',
          'MM': 'مم',
          'YYYY': 'YYYY',
          'Plate Number2': 'رقم اللوحة2',
          'Please enter a second plate number':
              'الرجاء إدخال رقم اللوحة الثانية',
          'Please enter a location': 'الرجاء إدخال الموقع',
          'Price': 'سعر',
          'Please enter a price': 'الرجاء إدخال السعر',
          'Please enter a description': 'الرجاء إدخال الوصف',
          'Choose Image': 'اختر الصورة',
          'Please enter': 'من فضلك أدخل',
          'Favorites & Saved': 'المفضلة والمحفوظة',
          'Order History': 'تاريخ الطلب',
          // 'order_history': 'تاريخ الطلب',
          'ID': 'المعرف',
          'Seller': 'البائع',
          'Buyer': 'المشتري',
          'Date': 'التاريخ',
          'Price': 'السعر',
          'Status': 'الحالة',
          'Private plate 195700': 'لوحة خاصة 195700',
          'Select Status': 'حدد الحالة',
          'New\nOrders': 'الطلبات\bالجديدة',
          'Inn\nProcess': 'قيد\nالمعالجة',
          'Delivery': 'توصيل',
          'Total\nDelivered': 'الإجمالي\nتم التسليم',
          'MeTrash': 'م',
          'Latest Orders': 'أحدث الطلبات',
          'Monday, 11 November \n2024(GMT-5)':
              'الاثنين، 11 نوفمبر \n2024 (توقيت جرينتش -5)',
          'Sold': 'مُباع',
          'Paid': 'مدفوع',
          'Unpaid': 'غير مدفوعة الأجر',
          'Pending': 'قيد الانتظار',
          'Success': 'نجاح',
          'Revenue': 'ربح',
          'Total Sales': 'إجمالي المبيعات',
          'Listed Items': 'العناصر المدرجة',
          'Pending \nPayments': '\nالدفعات المعلقة',
          'Payments': 'المدفوعات',
          'Payment History': 'تاريخ الدفع',
          'Basic Information': 'المعلومات الأساسية'
        },
      };
}
